ALTER TABLE tasks ADD COLUMN title TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN location TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN todos TEXT NOT NULL DEFAULT '[]';
UPDATE tasks SET title=content;
